### ISSUE TITLE
KHR_draco_mesh_compression - io.write - TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by timknip** [donmccurdy/glTF-Transform#143]
When using the `KHR_draco_mesh_compression` and trying to write a glTF document `TypeError: Cannot read property 'apply' of undefined` is thrown.

When I wrap `io.write()` in a `setTimeout` all is well.

Looks like the draco wasm Module is not fully loaded when calling `io.write()`
Might be related to https://github.com/google/draco/issues/600 

Here's my test code: https://gist.github.com/timknip/4ae9dbeda56f9f110bb43a3a88192b46

Stacktrace:
```
    TypeError: Cannot read property 'apply' of undefined
      at Module._emscripten_bind_Encoder_Encoder_0 (node_modules\draco3dgltf\draco_encoder_gltf_nodejs.js:39:23094)
      at new Encoder (node_modules\draco3dgltf\draco_encoder_gltf_nodejs.js:39:50343)
      at _ (node_modules\@gltf-transform\extensions\dist\extensions.js:1:3212)
      at n.o.prewrite (node_modules\@gltf-transform\extensions\dist\extensions.js:1:8416)
      at D:\github\floorplanner\fp.gltf\node_modules\@gltf-transform\core\dist\core.js:1:60298
      at Array.forEach (<anonymous>)
      at Function.t.write (node_modules\@gltf-transform\core\dist\core.js:1:60269)
      at n.writeJSON (node_modules\@gltf-transform\core\dist\core.js:1:67509)
      at n.writeBinary (node_modules\@gltf-transform\core\dist\core.js:1:68098)
      at n.r.Vt (node_modules\@gltf-transform\core\dist\core.js:1:70077)
      at n.r.write (node_modules\@gltf-transform\core\dist\core.js:1:68981)
      at draco_extension_issue (src\index.js:160:12)
      at Context.<anonymous> (test\index.spec.js:7:15)
      at processImmediate (internal/timers.js:461:21)
```

```
win 10, node 12.19.1
"@gltf-transform/core": "^0.8.0",
"@gltf-transform/extensions": "^0.8.0",
"@gltf-transform/lib": "^0.8.0",
 "draco3dgltf": "^1.3.6"
```

**Comment by donmccurdy** [comment]
I think you're correct that this is related to https://github.com/google/draco/issues/600. I haven't seen the issue when using the CLI, presumably because the CLI inherently has a short delay while the module loads.

The easiest fix would be to make either `io.write` (and `io.read`, probably) or `io.registerExtensions` asynchronous, I guess? Or perhaps there's some way to initialize Draco synchronously...

**Comment by timknip** [comment]
Note: defining 
```
const decoderModule = draco3d.createDecoderModule({});
const encoderModule = draco3d.createEncoderModule({});
```
somewhere in top of the module seem to fix it: https://gist.github.com/timknip/f6edbb878b88c56311e21e73df5b5576

Perhaps not a completely satisfactory solution, but making `io.read`, `io.write` or `io.registerExtensions` asynchronous might be overkill?

**Comment by donmccurdy** [comment]
> defining [both WASM modules] somewhere in top of the module seem to fix it

That's good, maybe what this needs is just a clearer error message when trying to use the encoder or decoder before it's ready?

> but making io.read, io.write or io.registerExtensions asynchronous might be overkill?

Yeah, I'd like to avoid that if we can.

**Comment by donmccurdy** [comment]
Looks like the next version of the Draco library returns a Promise from `draco3d.createDecoderModule({});` anyway, so this issue may just go away on its own. I'm planning to update the CLI to that soon, and will update the documentation to reflect this change.
