### ISSUE TITLE
Draco encoder, "Error compressing attribute"

### ISSUE THREAD

**Issue by Usnul** [donmccurdy/glTF-Transform#170]
I ran into this peculiar error:

```
Error: Error compressing "COLOR_0" attribute.
```

It comes from here:
https://github.com/donmccurdy/glTF-Transform/blob/1ef6be94787c4c6dcb21d011d219de73b0ff0e8a/packages/extensions/src/khr-draco-mesh-compression/encoder.ts#L80

I did a bit of digging and can verify a few things:
* The attribute seems to be created on the `Mesh` object created by the encoder module via `const mesh = new encoderModule.Mesh();`, as the value of `mesh.num_attributes()` is 7, and this happens to be the 7th, and last one.
* `attribute.getComponentType()` is `‌5126` (that's the same value as `Accessor.ComponentType.FLOAT`)
* `attribute.getCount()` is `450`
* `attribute.getElementSize()` is `4`
* `attribute.getArray()` is a `Float32Array` of size `1800`, this checks out as `450 * 4`

Since the result value is just `-1`, I'm having a bit of a difficulty understanding the reason for this failure.

**Comment by donmccurdy** [comment]
Hmm, I'm not sure what to make of that error, but thanks for sharing the debugging details!

If you're not able to share the model, would you mind checking whether glTF-Pipeline is able to compress this model correctly?

**Comment by Usnul** [comment]
Yeah, sorry, can't share the model. I have tried `gltf-pipeline`, it was unable to write read the file and convert it into draco-encoded output, but it was able to read the file and convert it (seemingly correctly) into an uncompressed gltf

```
>  gltf-pipeline -i "./resources/model.gltf" -o "./out/model.gltf" -d
Error
    at new RuntimeError ([redacted]\node_modules\gltf-pipeline\node_modules\cesium\Build\CesiumUnminified\Cesium.js:6780:13)
    at [redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:201:23
    at Function.ForEach.meshPrimitive ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:219:27)
    at [redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:116:17
    at Function.ForEach.object ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:45:27)
    at Function.ForEach.topLevel ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:64:20)
    at Function.ForEach.mesh ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:210:20)
    at compress ([redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:115:13)
    at [redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:60:20
    at tryCatcher ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\async.js:102:5) {
  message: 'Error: Draco encoding failed.'
}
```

However, this worked fine:
```
> gltf-pipeline -i "./resources/model.gltf" -o "./out/model.gltf" -s
Total: 134.861ms
```


Trying to re-compress the uncompressed file (because, why not?), same error occurs:
```
gltf-pipeline -i ./out/model.gltf -o ./out/draco/model.gltf -d -s
Error
    at new RuntimeError ([redacted]\node_modules\gltf-pipeline\node_modules\cesium\Build\CesiumUnminified\Cesium.js:6780:13)
    at [redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:201:23
    at Function.ForEach.meshPrimitive ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:219:27)
    at [redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:116:17
    at Function.ForEach.object ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:45:27)
    at Function.ForEach.topLevel ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:64:20)
    at Function.ForEach.mesh ([redacted]\node_modules\gltf-pipeline\lib\ForEach.js:210:20)
    at compress ([redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:115:13)
    at [redacted]\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:60:20
    at tryCatcher ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues ([redacted]\node_modules\gltf-pipeline\node_modules\bluebird\js\release\async.js:102:5) {
  message: 'Error: Draco encoding failed.'
}
```

**Comment by Usnul** [comment]
Whelp, scratch that, looked at the "successfully" converted model and it retains draco compression.

**Comment by donmccurdy** [comment]
Which steps lead to a successfully converted and compressed model?

Another idea to try would be higher values (16?) of the `--quantizeColor` option.

I've tried running a batch conversion over ~50 samples I had on hand, and couldn't reproduce this error for any of them, so I think I may need to leave this open until someone can share a reproducible case. It may be that I've implemented something incorrectly here, but glTF-Pipeline also pre-processes the data a bit more, so I wonder if that is just smoothing out some edge case that the Draco encoder doesn't like.

**Comment by Usnul** [comment]
Original model was compressed to draco with blender plugin, here are details:

```
"generator": "Khronos glTF Blender I/O v1.3.48"
```


```
"glTF2ExportSettings": {
          "export_all_influences": 0,
          "export_animations": 1,
          "export_apply": 1,
          "export_cameras": 0,
          "export_colors": 1,
          "export_copyright": "Moicon",
          "export_current_frame": 0,
          "export_def_bones": 0,
          "export_displacement": 0,
          "export_draco_generic_quantization": 12,
          "export_draco_mesh_compression_enable": 1,
          "export_draco_mesh_compression_level": 6,
          "export_draco_normal_quantization": 10,
          "export_draco_position_quantization": 14,
          "export_draco_texcoord_quantization": 12,
          "export_extras": 1,
          "export_force_sampling": 1,
          "export_format": "GLTF_SEPARATE",
          "export_frame_range": 1,
          "export_frame_step": 1,
          "export_image_format": "AUTO",
          "export_lights": 0,
          "export_materials": 1,
          "export_morph": 1,
          "export_morph_normal": 1,
          "export_morph_tangent": 0,
          "export_nla_strips": 1,
          "export_normals": 1,
          "export_selected": 0,
          "export_skins": 1,
          "export_tangents": 0,
          "export_texcoords": 1,
          "export_texture_dir": "",
          "export_yup": 1,
          "use_selection": 1
        }
```

**Comment by donmccurdy** [comment]
Sorry, I haven't been able to find a way to reproduce this issue. If this error comes up again with a model you are able to share, please let me know!
