### ISSUE TITLE
Fails to read glb files

### ISSUE THREAD

**Issue by garyo** [donmccurdy/glTF-Transform#26]
Hi; I know this is in development, so feel free to close if this isn't expected to be working yet. I came here because of the de-duplication idea (based on Matt Deslaurier's [gist](https://gist.github.com/mattdesl/aea40285e2d73916b6b9101b36d84da8)). 
I cloned the repo, did `npm install`, `lerna bootstrap`, and `npm run dist`, then ran `node_modules/.bin/gltf-transform analyze DamagedHelmet.glb` and got this error:
```
/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:600
        if (bufferView.byteLength > 0) {
                       ^

TypeError: Cannot read property 'byteLength' of undefined
    at Function.removeBufferView (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:600:24)
    at forEach (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:236:22)
    at Array.forEach (<anonymous>)
    at PackedGLTFContainer.unpack (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:231:29)
    at Function.fromGLB (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:338:54)
    at NodeIO.readGLB (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:766:25)
    at NodeIO.read (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:761:29)
    at Command.program.command.argument.action [as _action] (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/src/cli.js:26:30)
    at Command._run (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/node_modules/caporal/lib/command.js:413:40)
    at Program._run (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/node_modules/caporal/lib/program.js:170:16)
    at Program.parse (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/node_modules/caporal/lib/program.js:276:17)
    at Object.<anonymous> (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/src/cli.js:99:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```
If I load my own model, I get a slightly different error:
```
/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:91
                throw new Error(`Empty top-level array, "${this.json[key]}".`);
                ^

Error: Empty top-level array, "".
    at GLTFContainer.validate (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:91:23)
    at PackedGLTFContainer.unpack (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:241:19)
    at Function.fromGLB (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:338:54)
    at NodeIO.readGLB (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:766:25)
    at NodeIO.read (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/node_modules/@gltf-transform/core/dist/gltf-transform-core.js:761:29)
    at Command.program.command.argument.action [as _action] (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/src/cli.js:26:30)
    at Command._run (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/node_modules/caporal/lib/command.js:413:40)
    at Program._run (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/node_modules/caporal/lib/program.js:170:16)
    at Program.parse (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/node_modules/caporal/lib/program.js:276:17)
    at Object.<anonymous> (/c/DSS/Product/Horizon/WebProjects/horizon-project/horizon-data-converters/glTF-Transform/packages/cli/src/cli.js:99:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

(I tried modifying packages/core/src/packed-container.ts to see if I could print the "key" it's looking for, and re-running `npm run dist` but it didn't pick up my changes -- I'm not a lerna person so I assume I missed a step.)

**Comment by donmccurdy** [comment]
Are you able to share one of the GLB files that isn't working? You can drag ZIP archives into GitHub comments.

It's typically easier to install the CLI with npm, with `npm install --global @gltf-transform/cli`

**Comment by garyo** [comment]
I will get one for you for the second error, but I used the standard "Damaged Helmet" sample to get the first error: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet

I will try the standard npm install -- definitely possible I missed something in the build process.

**Comment by garyo** [comment]
Hi -- I fixed my own model (it had no materials!), and that works OK now with the npm-installed version of `gltf-transform`. But just FYI, that version still fails to analyze the DamagedHelmet sample referred to above (and attached here) with the same `TypeError` in my initial report.

[DamagedHelmet.zip](https://github.com/donmccurdy/glTF-Transform/files/3922439/DamagedHelmet.zip)

**Comment by anupamdas2012** [comment]
hi, I too am getting a "Cannot read property 'byteLength' of undefined" I tried it with the above mentioned DamagedHelmet.zip using the npm installed CLI and that is giving me the exact same error. even when i do a gltf-transform analyze DamagedHelmet.zip. Please advise

**Comment by donmccurdy** [comment]
Sorry for the delay — I am working on this.

**Comment by donmccurdy** [comment]
The good news is that the issue is fixed; the bad news is that it'll still be a while before the next release. v0.2 should be more stable.
