### ISSUE TITLE
when i require any extention from @gltf-transform/extensions library and run, the console will report error

### ISSUE THREAD

**Issue by Gongyouhai** [donmccurdy/glTF-Transform#553]
**Describe the bug**
when i update this library to the latest, as long as require any extention from @gltf-transform/extensions library, no matter use it or not, running the code will report a error

**To Reproduce**
1. import NodeIO and KHRONOS_EXTENSIONS extention
```
const { NodeIO } = require("@gltf-transform/core");
const { KHRONOS_EXTENSIONS } = require("@gltf-transform/extensions");
```
2. run the code
3. console will report error
error as follows:
```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (e:\StudyProject\JavaScript2\glTF2\meshopt\MeshoptCompressHigh2.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```
**Expected behavior**
no error report.

**Versions:**
 - Version: [v2.0.X]
 - Environment: [Node.js]

**Additional context**

**Comment by donmccurdy** [comment]
This library requires Node.js v14+, and based on the error it sounds like you might have Node.js v12 or lower installed. I'd recommend [Node Version Manager (nvm)](https://github.com/nvm-sh/nvm) if you're looking for a way to use multiple versions of Node.js.

**Comment by Gongyouhai** [comment]
It's ok, thanks !
