### ISSUE TITLE
Call to "weld" function leads to exception "TypeError: C.Encoder is not a constructor"

### ISSUE THREAD

**Issue by xtassin** [donmccurdy/glTF-Transform#686]
**Describe the bug**
The following code leads to the aforementioned exception:
`await document.transform(
        weld({ tolerance: 0.01 })
    );`

**Versions:**
 - Version: @gltf-transform/functions@2.4.3
 - Environment: Node.js v14.17.0 on Windows

**Additional context**
The function is called on non indexed geometry (single primitive/mesh).

**Comment by donmccurdy** [comment]
Based on the error, it sounds like you might be processing a glTF document with Draco or Meshopt compression. Does the error occur at this line? Or later when you write back to disk? If you could share an example file that may help as well.

**Comment by xtassin** [comment]
The exception. indeed, seems to be coming from DracoMeshCompression. I had to weld the mesh in order for Draco compression to quick in. Sorry for the confusion. 

Here is the stack trace:

```
(node:17364) UnhandledPromiseRejectionWarning: TypeError: C.Encoder is not a constructor
    at j (----------------------------------\js\node_modules\@gltf-transform\extensions\dist\extensions.js:1:12522)
    at k.prewrite (----------------------------------\js\node_modules\@gltf-transform\extensions\dist\extensions.js:1:19329)
    at ----------------------------------\js\node_modules\@gltf-transform\core\dist\core.js:1:52609
    at Array.forEach (<anonymous>)
    at Function.write (----------------------------------\js\node_modules\@gltf-transform\core\dist\core.js:1:52596)
    at exports.NodeIO.writeJSON (----------------------------------\js\node_modules\@gltf-transform\core\dist\core.js:1:59638)
    at exports.NodeIO.writeBinary (----------------------------------\js\node_modules\@gltf-transform\core\dist\core.js:1:59870)
    at exports.NodeIO.Y (----------------------------------\js\node_modules\@gltf-transform\core\dist\core.js:1:67519)
    at exports.NodeIO.write (----------------------------------\js\node_modules\@gltf-transform\core\dist\core.js:1:66636)
    at writeGLTF (----------------------------------\js\mesh.js:2038:14)
```

Exception appears when I try Draco compression after welding with the following code:

```
let io = new NodeIO()
	.registerExtensions([DracoMeshCompression])
	.registerDependencies({
		"draco3d.encoder": draco3d.createEncoderModule()
	});

document.createExtension(DracoMeshCompression)
	.setRequired(true)
	.setEncoderOptions({
		method: DracoMeshCompression.EncoderMethod.EDGEBREAKER,
		encodeSpeed: 5
	});

await io.write("--------------------------------------/file.glb", document);
```

I attach the GLB file generated without compression or welding if that may help.

Thank you for your help!

[file.zip](https://github.com/donmccurdy/glTF-Transform/files/9594458/file.zip)

**Comment by donmccurdy** [comment]
The function `draco3d.createEncoderModule()` will return a Promise — may just need to await its result here!

**Comment by xtassin** [comment]
Definitely! My bad. Thank you very much for your help.
