### ISSUE TITLE
oxipng not working in CLI in node 18

### ISSUE THREAD

**Issue by gmarty** [donmccurdy/glTF-Transform#773]
**Describe the bug**
I got an error message when running `oxipng` from the CLI in node 18 and 19 (works in node 14).

**To Reproduce**
1. Use node 18 (e.g. with nvm `nvm use 18`.
2. Run an `oxipng` command:
  ```sh
  gltf-transform oxipng scene.glb optimised.glb
  ```
3. See the error message and the glb file is not processed.

**Expected behavior**
An optimised glb file should be crreated.

**Versions:**
 - Version: 2.5.1
 - Environment: Node 18 on MacOs Ventura 13.1

**Additional context**
Full error message (ignore the Fetch API experimental warnings). The message is the same in Node 19 (minus the warning):
```
(node:63536) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

error: Failed to parse URL from /Users/g/.nvm/versions/node/v18.12.1/lib/node_modules/@gltf-transform/cli/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm

(node:63536) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:63536) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

node:internal/event_target:1006
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Failed to parse URL from /Users/g/.nvm/versions/node/v18.12.1/lib/node_modules/@gltf-transform/cli/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at instantiateAsync (/Users/g/.nvm/versions/node/v18.12.1/lib/node_modules/@gltf-transform/cli/node_modules/@squoosh/lib/build/index.js:28:11469)
      at createWasm (/Users/g/.nvm/versions/node/v18.12.1/lib/node_modules/@gltf-transform/cli/node_modules/@squoosh/lib/build/index.js:28:12079)
      at /Users/g/.nvm/versions/node/v18.12.1/lib/node_modules/@gltf-transform/cli/node_modules/@squoosh/lib/build/index.js:28:35216
}

Node.js v18.12.1
```

**Comment by donmccurdy** [comment]
Hi @gmarty — see https://github.com/donmccurdy/glTF-Transform/issues/751, unfortunately the `@squoosh/lib` library that I'm using for image compression is no longer maintained, and does not support Node.js v18. I'm in the process of changing that dependency, if you'd like to get a pre-release version of glTF Transform v3 you can try:

```bash
npm install --global @gltf-transform/cli@next
```

**Comment by gmarty** [comment]
Thank you for your reply.
I'll go ahead and close it as duplicate.
