### ISSUE TITLE
`setExtension` fails when trying to call `_validateParent`

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Transform#856]
**Describe the bug**
When calling `setExtension` on e.g. a texture during `read` I'm getting an error caused by `_validateParent` not being defined 

``md
TypeError: e.t is not a function
    at wt.setExtension (file:///C:/git/needle-gltf-extensions/modules/glTF-Transform/packages/core/dist/core.modern.js:1:13709)
    at C:\git\needle-gltf-extensions\package\dist\extensions\NEEDLE_compression_texture\NEEDLE_compression_texture.js:26:21
    at Array.forEach (<anonymous>)
```

**To Reproduce**
Steps to reproduce the behavior:
1. create custom extension
2. during `read` get textures and try to add a extension to one of the textures

**Expected behavior**
no exception, extension is added

**Versions:**
 - Version: 3.1.1
 - Environment: node 18

**Additional context**

```ts
export const EXTENSION_NAME = "NEEDLE_compression_texture";

export declare interface NEEDLE_compression_texture_schema {
    mode: string;
    slot: string;
    /** quality in range of 0 - 1 */
    quality: number;
    maxSize: number;
}

const debugLog = false;

export class NEEDLE_compression_texture extends Extension {

    static EXTENSION_NAME = EXTENSION_NAME;
    extensionName: string = EXTENSION_NAME;

    create(toktxInfo: NEEDLE_compression_texture_schema) {
        const ext = new NEEDLE_compression_texture_property(this.document.getGraph(), "");
        ext.model = toktxInfo;
        return ext;
    }

    read(context: ReaderContext): this {
        if (!context.jsonDoc.json.textures) return;
        if (debugLog) console.log("READ " + EXTENSION_NAME);
        context.textures?.forEach((tex, _) => {
            const textureDefinition = getTextureDefinition(context, tex)
            if (textureDefinition?.extensions && textureDefinition.extensions[EXTENSION_NAME]) {
                const prop = new NEEDLE_compression_texture_property(this.document.getGraph(), EXTENSION_NAME);
                prop.model = textureDefinition.extensions[EXTENSION_NAME] as NEEDLE_compression_texture_schema;
                tex.setExtension(EXTENSION_NAME, prop);
            }
        });
        return this;
    }

    write(context: WriterContext): this {
        if (debugLog) console.log("WRITE " + EXTENSION_NAME);
        const root = this.document.getRoot();
        const textures = root.listTextures();
        for (const tex of textures) {
            const ext = tex.getExtension(EXTENSION_NAME) as NEEDLE_compression_texture_property;
            if (ext) {
                const def = getTextureDefinition(context, tex);
                if (def) {
                    def.extensions = def.extensions || {};
                    def.extensions[EXTENSION_NAME] = ext.model;
                }
            }
        }
        return this;
    }
}

export class NEEDLE_compression_texture_property extends ExtensionProperty {
    static EXTENSION_NAME = EXTENSION_NAME;
    readonly extensionName: string = EXTENSION_NAME;
    parentTypes: PropertyType[] = [PropertyType.TEXTURE];
    propertyType = EXTENSION_NAME;
    init(): void { }
    model: NEEDLE_compression_texture_schema;
}

```

**Comment by donmccurdy** [comment]
Let's move this to a discussion — we have a lot of extensions implemented without this error, so until/unless this is reproducible as a clear bug, I'm guessing it will be more of a discussion around extension implementation.
